const std = @import("std");
const testing = std.testing;

// ============================================================================
// Schema core: change listeners sharing one decoder, change-record ownership,
// and the callbacks layer held against @colyseus/schema's own Callbacks.
//
// tests/schema/schema_core_fixtures.zig is generated by
// tests/schema/generate-schema-core-fixtures.ts: patches from the 5.0 Encoder
// + StateView, and per step the log its Callbacks produce for them. The log
// tests replay the generator's registrations and must match it line for line.
// ============================================================================

const c = @cImport({
    @cInclude("colyseus/schema.h");
    @cInclude("colyseus/schema/decoder.h");
    @cInclude("colyseus/schema/callbacks.h");
    @cInclude("colyseus/schema/collections.h");
    @cInclude("colyseus/room_clock.h");
    @cInclude("colyseus/predict/predict.h");
    @cInclude("schema/core_state.h");
});
const fx = @import("schema/schema_core_fixtures.zig");

// ============================================================================
// Helpers
// ============================================================================

fn decode(decoder: [*c]c.colyseus_decoder_t, bytes: []const u8) void {
    var it = c.colyseus_iterator_t{ .offset = 0 };
    c.colyseus_decoder_decode(decoder, bytes.ptr, bytes.len, &it);
}

fn deliver(decoder: [*c]c.colyseus_decoder_t, step: fx.Step) void {
    for (step.patches) |patch| decode(decoder, patch);
}

fn stepIndex(name: []const u8) usize {
    for (fx.steps, 0..) |step, i| {
        if (std.mem.eql(u8, step.name, name)) return i;
    }
    @panic("no such fixture step");
}

/// Reflection handshake → dynamic vtables, the path every engine binding takes.
const Dyn = struct {
    serializer: [*c]c.colyseus_schema_serializer_t,

    fn open() Dyn {
        const serializer = c.colyseus_schema_serializer_create(null);
        const reflection: []const u8 = fx.reflection;
        c.colyseus_schema_serializer_handshake(serializer, reflection.ptr, reflection.len, 0);
        return .{ .serializer = serializer };
    }

    fn decoder(self: Dyn) [*c]c.colyseus_decoder_t {
        return self.serializer.*.decoder;
    }

    fn root(self: Dyn) ?*anyopaque {
        return @ptrCast(c.colyseus_decoder_get_state(self.decoder()));
    }

    fn close(self: Dyn) void {
        c.colyseus_schema_serializer_free(self.serializer);
    }
};

/// Codegen'd vtables (tests/schema/core_state.h).
fn openStatic() [*c]c.colyseus_decoder_t {
    return c.colyseus_decoder_create(&c.core_state_vtable);
}

fn closeStatic(decoder: [*c]c.colyseus_decoder_t) void {
    c.colyseus_decoder_release_codegen_tree(decoder);
    c.colyseus_decoder_free(decoder);
}

const Log = struct {
    buf: [48][96]u8 = undefined,
    lens: [48]usize = undefined,
    count: usize = 0,

    fn push(self: *Log, comptime format: []const u8, args: anytype) void {
        std.debug.assert(self.count < self.buf.len);
        const line_ = std.fmt.bufPrint(&self.buf[self.count], format, args) catch unreachable;
        self.lens[self.count] = line_.len;
        self.count += 1;
    }

    fn line(self: *const Log, i: usize) []const u8 {
        return self.buf[i][0..self.lens[i]];
    }

    fn expect(self: *const Log, label: []const u8, want: []const []const u8) !void {
        var ok = self.count == want.len;
        if (ok) {
            for (want, 0..) |w, i| {
                if (!std.mem.eql(u8, w, self.line(i))) {
                    ok = false;
                    break;
                }
            }
        }
        if (ok) return;
        std.debug.print("\n{s}\n  want:\n", .{label});
        for (want) |w| std.debug.print("    {s}\n", .{w});
        std.debug.print("  got:\n", .{});
        for (0..self.count) |i| std.debug.print("    {s}\n", .{self.line(i)});
        return error.LogMismatch;
    }
};

fn strOf(p: ?*anyopaque) []const u8 {
    const ptr = p orelse return "undefined";
    return std.mem.span(@as([*:0]const u8, @ptrCast(ptr)));
}

fn numOf(buf: []u8, p: ?*anyopaque) []const u8 {
    const ptr = p orelse return "undefined";
    const v = @as(*const f64, @ptrCast(@alignCast(ptr))).*;
    if (v == @floor(v)) return std.fmt.bufPrint(buf, "{d}", .{@as(i64, @intFromFloat(v))}) catch unreachable;
    return std.fmt.bufPrint(buf, "{d}", .{v}) catch unreachable;
}

// ============================================================================
// The generator's registrations, mirrored
// ============================================================================

const Mode = enum { reflection, codegen };

const EntCtx = struct {
    rec: *Recorder,
    key: [8]u8 = undefined,
    key_len: usize = 0,
};

const Recorder = struct {
    mode: Mode,
    cb: ?*c.colyseus_callbacks_t = null,
    root: ?*anyopaque = null,
    log: Log = .{},
    removed_once: bool = false,
    ents: [16]EntCtx = undefined,
    ent_count: usize = 0,

    /// Made before the first state arrives, like a room's on_join.
    fn register(self: *Recorder) void {
        _ = c.colyseus_callbacks_listen(self.cb, self.root, "title", onTitle, self, true);
        _ = c.colyseus_callbacks_on_add(self.cb, self.root, "ents", onAdd, self, true);
        _ = c.colyseus_callbacks_on_remove(self.cb, self.root, "ents", onRemove, self);
    }

    fn run(self: *Recorder, decoder: [*c]c.colyseus_decoder_t, steps: []const fx.Step) !void {
        for (steps) |step| {
            self.log.count = 0;
            deliver(decoder, step);

            var want_lines: [32][]const u8 = undefined;
            var bufs: [32][96]u8 = undefined;
            for (step.log, 0..) |want, i| want_lines[i] = self.expected(want, &bufs[i]);

            var label: [64]u8 = undefined;
            try self.log.expect(
                std.fmt.bufPrint(&label, "[{s}] step \"{s}\"", .{ @tagName(self.mode), step.name }) catch unreachable,
                want_lines[0..step.log.len],
            );
        }
    }

    /// A codegen'd number has no "unset" state: its first previous value is 0.
    fn expected(self: *const Recorder, want: []const u8, buf: []u8) []const u8 {
        const unset = " undefined";
        if (self.mode == .codegen and std.mem.startsWith(u8, want, "x ") and std.mem.endsWith(u8, want, unset)) {
            return std.fmt.bufPrint(buf, "{s} 0", .{want[0 .. want.len - unset.len]}) catch unreachable;
        }
        return want;
    }
};

fn recorderOf(ud: ?*anyopaque) *Recorder {
    return @ptrCast(@alignCast(ud.?));
}

fn onTitle(value: ?*anyopaque, prev: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    recorderOf(ud).log.push("title {s} {s}", .{ strOf(value), strOf(prev) });
}

fn onTitle2(value: ?*anyopaque, prev: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    recorderOf(ud).log.push("title2 {s} {s}", .{ strOf(value), strOf(prev) });
}

fn onAdd(value: ?*anyopaque, key: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    const rec = recorderOf(ud);
    const k = strOf(key);
    rec.log.push("add {s}", .{k});

    const ent = &rec.ents[rec.ent_count];
    rec.ent_count += 1;
    ent.* = .{ .rec = rec, .key_len = k.len };
    @memcpy(ent.key[0..k.len], k);
    _ = c.colyseus_callbacks_listen(rec.cb, value, "x", onX, ent, true);
    _ = c.colyseus_callbacks_listen(rec.cb, value, "label", onLabel, ent, true);
}

fn onRemove(value: ?*anyopaque, key: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    _ = value;
    const rec = recorderOf(ud);
    rec.log.push("remove {s}", .{strOf(key)});
    if (!rec.removed_once) {
        rec.removed_once = true;
        _ = c.colyseus_callbacks_listen(rec.cb, rec.root, "title", onTitle2, rec, true);
    }
}

fn onX(value: ?*anyopaque, prev: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    const ent: *EntCtx = @ptrCast(@alignCast(ud.?));
    var a: [32]u8 = undefined;
    var b: [32]u8 = undefined;
    ent.rec.log.push("x {s} {s} {s}", .{ ent.key[0..ent.key_len], numOf(&a, value), numOf(&b, prev) });
}

fn onLabel(value: ?*anyopaque, prev: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    const ent: *EntCtx = @ptrCast(@alignCast(ud.?));
    ent.rec.log.push("label {s} {s} {s}", .{ ent.key[0..ent.key_len], strOf(value), strOf(prev) });
}

// ============================================================================
// Callbacks vs @colyseus/schema — registered before the first state.
// Covers: join replay order, value-equal re-sends reporting nothing, a fog
// re-add reusing the refId without inheriting the old instance's listeners,
// immediate skipped inside a trigger (title2), add/remove/field ordering in
// one patch, and a collection field swapped for a new one.
// ============================================================================

// A binding may free its callbacks layer after the room (GameMaker did): the
// layer's free must not reach into the decoder that died first. The junk
// allocation takes the freed decoder's place, so a dangling read crashes.
test "callbacks_freed_after_their_decoder" {
    const decoder = c.colyseus_decoder_create(&c.core_state_vtable);
    const cb = c.colyseus_callbacks_create(decoder).?;
    c.colyseus_decoder_free(decoder);
    const junk: [*]u8 = @ptrCast(std.c.malloc(@sizeOf(c.colyseus_decoder_t)).?);
    defer std.c.free(junk);
    @memset(junk[0..@sizeOf(c.colyseus_decoder_t)], 0xAA);
    c.colyseus_callbacks_free(cb);
}

test "callbacks_match_ts_reflection" {
    const dyn = Dyn.open();
    defer dyn.close();

    var rec = Recorder{ .mode = .reflection };
    rec.cb = c.colyseus_callbacks_create(dyn.decoder()).?;
    defer c.colyseus_callbacks_free(rec.cb);
    rec.root = dyn.root();
    rec.register();

    try rec.run(dyn.decoder(), &fx.steps);
}

test "callbacks_match_ts_codegen" {
    const decoder = openStatic();
    defer closeStatic(decoder);

    var rec = Recorder{ .mode = .codegen };
    rec.cb = c.colyseus_callbacks_create(decoder).?;
    defer c.colyseus_callbacks_free(rec.cb);
    rec.root = @ptrCast(c.colyseus_decoder_get_state(decoder));
    rec.register();

    try rec.run(decoder, &fx.steps);
}

// ============================================================================
// A field set twice in one patch (fog re-add + delta): each record keeps the
// value its own op decoded, and owns it — nothing points into the instance.
// ============================================================================

fn captureRecords(changes: [*c]c.colyseus_changes_t, ud: ?*anyopaque) callconv(.c) void {
    const log: *Log = @ptrCast(@alignCast(ud.?));
    const list = changes.*;
    for (0..@intCast(list.count)) |i| {
        const change = list.items[i];
        if (change.field == null) continue;
        const name = std.mem.span(@as([*:0]const u8, @ptrCast(change.field)));
        const owned: []const u8 = if (change.owns_value) "owned" else "borrowed";
        var a: [32]u8 = undefined;
        var b: [32]u8 = undefined;
        if (std.mem.eql(u8, name, "x")) {
            log.push("x {s} {s} {s}", .{ numOf(&a, change.value), numOf(&b, change.previous_value), owned });
        } else if (std.mem.eql(u8, name, "label")) {
            log.push("label {s} {s} {s}", .{ strOf(change.value), strOf(change.previous_value), owned });
        }
    }
}

fn expectFogInRecords(decoder: [*c]c.colyseus_decoder_t, want: []const []const u8) !void {
    var log = Log{};
    try testing.expect(c.colyseus_decoder_set_trigger_callback(decoder, captureRecords, &log));
    defer c.colyseus_decoder_remove_trigger_callback(decoder, captureRecords, &log);

    const fog_in = stepIndex("fog_in");
    for (fx.steps[0..fog_in]) |step| deliver(decoder, step);
    log.count = 0;
    deliver(decoder, fx.steps[fog_in]);
    try log.expect("fog_in change records", want);
}

test "double_set_records_own_each_value" {
    {
        const dyn = Dyn.open();
        defer dyn.close();
        try expectFogInRecords(dyn.decoder(), &.{
            "x 11 undefined owned",
            "label bbbb undefined owned",
            "x 12 11 owned",
            "label bbbb2 bbbb owned",
        });
    }
    {
        const decoder = openStatic();
        defer closeStatic(decoder);
        try expectFogInRecords(decoder, &.{
            "x 11 0 owned",
            "label bbbb undefined owned",
            "x 12 11 owned",
            "label bbbb2 bbbb owned",
        });
    }
}

// ============================================================================
// Several change listeners on one decoder
// ============================================================================

var NOW: f64 = 1000;
fn scriptedNow() callconv(.c) f64 {
    return NOW;
}

fn attachTick(p: ?*c.colyseus_predict_t, root: ?*anyopaque) !void {
    var raw = std.mem.zeroes(c.colyseus_predict_field_options_t);
    raw.mode = c.COLYSEUS_PREDICT_RAW;
    const cfg = [_]c.colyseus_attach_field_t{.{ .field = "tick", .opts = &raw }};
    try testing.expectEqual(@as(c_int, 0), c.colyseus_predict_attach(p, @ptrCast(@alignCast(root)), &cfg, cfg.len));
}

/// RAW reads the predict slot, which only moves when predict's own listener fires.
fn predictedTick(p: ?*c.colyseus_predict_t, root: ?*anyopaque) f64 {
    NOW += 50;
    _ = c.colyseus_predict_tick(p, NOW);
    return c.colyseus_predict_value(p, @ptrCast(@alignCast(root)), "tick");
}

test "app_callbacks_survive_predict_hooking_the_same_decoder" {
    c.colyseus_room_clock_now_provider = scriptedNow;
    const dyn = Dyn.open();
    defer dyn.close();

    // the app's Callbacks first, at join...
    var rec = Recorder{ .mode = .reflection };
    rec.cb = c.colyseus_callbacks_create(dyn.decoder()).?;
    rec.root = dyn.root();
    rec.register();

    // ...then the predict layer's own callbacks, as a room creates them lazily
    const predict_cb = c.colyseus_callbacks_create(dyn.decoder()).?;
    defer c.colyseus_callbacks_free(predict_cb);
    const clock = c.colyseus_room_clock_create().?;
    defer c.colyseus_room_clock_free(clock);
    const p = c.colyseus_predict_create(predict_cb, clock).?;
    defer c.colyseus_predict_free(p);
    try attachTick(p, rec.root);

    try rec.run(dyn.decoder(), fx.steps[0..2]); // join + move: every app callback fires
    try testing.expectEqual(@as(f64, 2), predictedTick(p, rec.root));

    // dropping the app's layer leaves predict's listening
    c.colyseus_callbacks_free(rec.cb);
    rec.log.count = 0;
    deliver(dyn.decoder(), fx.steps[stepIndex("fog_out")]);
    try testing.expectEqual(@as(usize, 0), rec.log.count);
    try testing.expectEqual(@as(f64, 3), predictedTick(p, rec.root));
}

test "freeing_the_predict_layer_keeps_app_callbacks" {
    c.colyseus_room_clock_now_provider = scriptedNow;
    const dyn = Dyn.open();
    defer dyn.close();

    const predict_cb = c.colyseus_callbacks_create(dyn.decoder()).?;
    const clock = c.colyseus_room_clock_create().?;
    defer c.colyseus_room_clock_free(clock);
    const p = c.colyseus_predict_create(predict_cb, clock).?;
    try attachTick(p, dyn.root());

    var rec = Recorder{ .mode = .reflection };
    rec.cb = c.colyseus_callbacks_create(dyn.decoder()).?;
    defer c.colyseus_callbacks_free(rec.cb);
    rec.root = dyn.root();
    rec.register();

    try rec.run(dyn.decoder(), fx.steps[0..1]);
    try testing.expectEqual(@as(f64, 1), predictedTick(p, rec.root));

    c.colyseus_predict_free(p);
    c.colyseus_callbacks_free(predict_cb);
    try rec.run(dyn.decoder(), fx.steps[1..2]);
}

fn noopTrigger(changes: [*c]c.colyseus_changes_t, ud: ?*anyopaque) callconv(.c) void {
    _ = changes;
    _ = ud;
}

test "listener_table_full_fails_loudly" {
    const decoder = openStatic();
    defer closeStatic(decoder);

    var layers: [c.COLYSEUS_DECODER_MAX_TRIGGERS]*c.colyseus_callbacks_t = undefined;
    for (&layers) |*layer| layer.* = c.colyseus_callbacks_create(decoder).?;

    // both refusals also log to stderr
    try testing.expect(c.colyseus_callbacks_create(decoder) == null);
    try testing.expect(!c.colyseus_decoder_set_trigger_callback(decoder, noopTrigger, null));

    // a freed layer gives its slot back
    c.colyseus_callbacks_free(layers[0]);
    const again = c.colyseus_callbacks_create(decoder) orelse return error.SlotNotReleased;
    c.colyseus_callbacks_free(again);
    for (layers[1..]) |layer| c.colyseus_callbacks_free(layer);
}

var fired: [16]u8 = undefined;
var fired_len: usize = 0;

fn mark(n: u8) void {
    fired[fired_len] = n;
    fired_len += 1;
}

fn decoderOf(ud: ?*anyopaque) [*c]c.colyseus_decoder_t {
    return @ptrCast(@alignCast(ud.?));
}

fn removesNext(changes: [*c]c.colyseus_changes_t, ud: ?*anyopaque) callconv(.c) void {
    _ = changes;
    mark(1);
    c.colyseus_decoder_remove_trigger_callback(decoderOf(ud), removedByPrevious, ud);
}

fn removedByPrevious(changes: [*c]c.colyseus_changes_t, ud: ?*anyopaque) callconv(.c) void {
    _ = changes;
    _ = ud;
    mark(2);
}

fn last(changes: [*c]c.colyseus_changes_t, ud: ?*anyopaque) callconv(.c) void {
    _ = changes;
    _ = ud;
    mark(3);
}

fn removesItself(changes: [*c]c.colyseus_changes_t, ud: ?*anyopaque) callconv(.c) void {
    _ = changes;
    mark(4);
    c.colyseus_decoder_remove_trigger_callback(decoderOf(ud), removesItself, ud);
}

test "listener_removed_mid_dispatch_keeps_the_rest" {
    const decoder = openStatic();
    defer closeStatic(decoder);
    const ud: ?*anyopaque = @ptrCast(decoder);
    const patch = fx.steps[0].patches[0];

    try testing.expect(c.colyseus_decoder_set_trigger_callback(decoder, removesNext, ud));
    try testing.expect(c.colyseus_decoder_set_trigger_callback(decoder, removedByPrevious, ud));
    try testing.expect(c.colyseus_decoder_set_trigger_callback(decoder, last, ud));

    fired_len = 0;
    decode(decoder, patch);
    try testing.expectEqualSlices(u8, &.{ 1, 3 }, fired[0..fired_len]);

    c.colyseus_decoder_remove_trigger_callback(decoder, removesNext, ud);
    c.colyseus_decoder_remove_trigger_callback(decoder, last, ud);
    try testing.expect(c.colyseus_decoder_set_trigger_callback(decoder, removesItself, ud));
    try testing.expect(c.colyseus_decoder_set_trigger_callback(decoder, last, ud));

    fired_len = 0;
    decode(decoder, patch);
    decode(decoder, patch);
    try testing.expectEqualSlices(u8, &.{ 4, 3, 3 }, fired[0..fired_len]);
}

// ============================================================================
// `immediate` from inside a callback, across two layers on one decoder:
// exactly one delivery whichever layer dispatches first.
// ============================================================================

const Probe = struct {
    other: ?*c.colyseus_callbacks_t = null,
    calls: u32 = 0,
};

fn probeX(value: ?*anyopaque, prev: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    _ = value;
    _ = prev;
    const probe: *Probe = @ptrCast(@alignCast(ud.?));
    probe.calls += 1;
}

fn listenOnOtherLayer(value: ?*anyopaque, key: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    _ = key;
    const probe: *Probe = @ptrCast(@alignCast(ud.?));
    _ = c.colyseus_callbacks_listen(probe.other, value, "x", probeX, probe, true);
}

fn xDeliveriesAtJoin(registering_layer_first: bool) u32 {
    const dyn = Dyn.open();
    defer dyn.close();

    var registering: ?*c.colyseus_callbacks_t = null;
    var other: ?*c.colyseus_callbacks_t = null;
    if (registering_layer_first) {
        registering = c.colyseus_callbacks_create(dyn.decoder());
        other = c.colyseus_callbacks_create(dyn.decoder());
    } else {
        other = c.colyseus_callbacks_create(dyn.decoder());
        registering = c.colyseus_callbacks_create(dyn.decoder());
    }
    defer {
        c.colyseus_callbacks_free(registering);
        c.colyseus_callbacks_free(other);
    }

    var probe = Probe{ .other = other };
    _ = c.colyseus_callbacks_on_add(registering, dyn.root(), "ents", listenOnOtherLayer, &probe, true);
    deliver(dyn.decoder(), fx.steps[0]); // e1 + e2 arrive
    return probe.calls;
}

test "immediate_inside_a_callback_delivers_once_across_layers" {
    // the other layer dispatches later: its dispatch delivers x, immediate stays quiet
    try testing.expectEqual(@as(u32, 2), xDeliveriesAtJoin(true));
    // the other layer already dispatched: only immediate can deliver x
    try testing.expectEqual(@as(u32, 2), xDeliveriesAtJoin(false));
}

// ============================================================================
// A collection callback registered before its collection exists keeps the
// handle it returned: removing it unbinds the callback after it bound.
// ============================================================================

fn countAdd(value: ?*anyopaque, key: ?*anyopaque, ud: ?*anyopaque) callconv(.c) void {
    _ = value;
    _ = key;
    const n: *u32 = @ptrCast(@alignCast(ud.?));
    n.* += 1;
}

test "on_add_registered_before_state_keeps_its_handle" {
    const dyn = Dyn.open();
    defer dyn.close();
    const cb = c.colyseus_callbacks_create(dyn.decoder()).?;
    defer c.colyseus_callbacks_free(cb);

    var adds: u32 = 0;
    const handle = c.colyseus_callbacks_on_add(cb, dyn.root(), "ents", countAdd, &adds, true);
    try testing.expect(handle != c.COLYSEUS_INVALID_CALLBACK_HANDLE);

    deliver(dyn.decoder(), fx.steps[0]);
    try testing.expectEqual(@as(u32, 2), adds);

    c.colyseus_callbacks_remove(cb, handle);
    for (fx.steps[1..]) |step| deliver(dyn.decoder(), step); // e1 re-added, e3 added
    try testing.expectEqual(@as(u32, 2), adds);
}
