const std = @import("std");
const testing = std.testing;

// ============================================================================
// Phase 3 — input layer + RoomClock.
//
// Fixtures generated by colyseus-0.18 PORTING/generate-input-fixtures.cts
// (self-verified against the JS schema InputEncoder/InputDecoder, the real
// InputHandleImpl and RoomClockImpl). Contract:
// PORTING/sdk-ports-input-layer.md.
// ============================================================================

const c = @cImport({
    @cInclude("colyseus/protocol.h");
    @cInclude("colyseus/transport.h");
    @cInclude("colyseus/room.h");
    @cInclude("colyseus/room_clock.h");
    @cInclude("colyseus/input_handle.h");
    @cInclude("colyseus/schema.h");
    @cInclude("colyseus/schema/input_encoder.h");
    @cInclude("colyseus/schema/dynamic_schema.h");
    @cInclude("schema/move_input.h");
    @cInclude("schema/p0_state.h");
});

// ─── scripted clock: colyseus_room_clock_now_provider override ──────────────

var NOW: f64 = 0;
fn scriptedNow() callconv(.c) f64 {
    return NOW;
}

fn useScriptedNow() void {
    NOW = 0;
    c.colyseus_room_clock_now_provider = scriptedNow;
}

// ─── stub send/is_open/get_clock host for direct handle tests ───────────────

var sent_frames: [16][64]u8 = undefined;
var sent_lens: [16]usize = undefined;
var sent_count: usize = 0;
var stub_clock: ?*c.colyseus_room_clock_t = null;

fn stubSend(data: [*c]const u8, length: usize, userdata: ?*anyopaque) callconv(.c) void {
    _ = userdata;
    if (sent_count < sent_frames.len and length <= 64) {
        @memcpy(sent_frames[sent_count][0..length], data[0..length]);
        sent_lens[sent_count] = length;
        sent_count += 1;
    }
}

fn stubIsOpen(userdata: ?*anyopaque) callconv(.c) bool {
    _ = userdata;
    return true;
}

fn stubGetClock(userdata: ?*anyopaque) callconv(.c) ?*c.colyseus_room_clock_t {
    _ = userdata;
    return stub_clock;
}

fn expectFrame(index: usize, expected: []const u8) !void {
    try testing.expectEqual(expected.len, sent_lens[index]);
    try testing.expectEqualSlices(u8, expected, sent_frames[index][0..sent_lens[index]]);
}

const HandleCtx = struct {
    instance: *c.move_input_t,
    handle: *c.colyseus_input_handle_t,
};

fn makeHandle(unreliable: bool, stamp_render: bool, stamp_reckon: bool, render_delay: f64) HandleCtx {
    sent_count = 0;
    const instance = c.move_input_create().?;
    instance.*.__base.__vtable = &c.move_input_vtable;
    const encoder = c.colyseus_input_encoder_create(
        @ptrCast(instance), &c.move_input_vtable, unreliable, 3).?;
    var options = std.mem.zeroes(c.colyseus_input_options_t);
    options.render_delay = render_delay;
    const handle = c.colyseus_input_handle_create(
        @ptrCast(instance), &c.move_input_vtable, encoder,
        stamp_render, stamp_reckon, &options, 0, 0, 0,
        stubSend, stubIsOpen, stubGetClock, null).?;
    return .{ .instance = instance, .handle = handle };
}

fn destroyHandle(ctx: HandleCtx) void {
    // The handle owns the bound instance (see colyseus_input_handle_free) —
    // destroying it here too is a double free. Older allocators let that slide;
    // macOS 15's hardened xzone malloc traps on it.
    c.colyseus_input_handle_free(ctx.handle);
}

/// Seed a real clock into an exactly-scripted state: one sample at tNow=1000
/// with sNow=500, rtt=80 → offset = 500+40−1000 = −460 (exact), smoothedRtt =
/// 80 (seed), lastServerTime = 500 > 0 (synced). serverNow(T) = T − 460.
fn makeSyncedClock() *c.colyseus_room_clock_t {
    const clock = c.colyseus_room_clock_create().?;
    NOW = 1000;
    c.colyseus_room_clock_sample(clock, 500, 80);
    return clock;
}

// ─── encoder ────────────────────────────────────────────────────────────────

test "input_encoder_reliable" {
    const instance = c.move_input_create().?;
    defer c.move_input_vtable.destroy.?(@ptrCast(instance));
    const encoder = c.colyseus_input_encoder_create(
        @ptrCast(instance), &c.move_input_vtable, false, 0).?;
    defer c.colyseus_input_encoder_free(encoder);

    var out_len: usize = 0;

    instance.*.vx = 1.5;
    instance.*.vy = -2;
    instance.*.jump = true;
    instance.*.action = 3;
    var out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqualSlices(u8, &[_]u8{ 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3 }, out[0..out_len]);

    instance.*.vx = 2.5;
    out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqualSlices(u8, &[_]u8{ 128, 202, 0, 0, 32, 64 }, out[0..out_len]);

    // no change → empty body
    out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqual(@as(usize, 0), out_len);

    instance.*.jump = false;
    instance.*.action = 7;
    out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqualSlices(u8, &[_]u8{ 130, 0, 131, 7 }, out[0..out_len]);

    // reset → full snapshot of populated fields
    c.colyseus_input_encoder_reset(encoder);
    out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqualSlices(u8, &[_]u8{ 128, 202, 0, 0, 32, 64, 129, 254, 130, 0, 131, 7 }, out[0..out_len]);
}

test "input_encoder_unreliable" {
    const instance = c.move_input_create().?;
    defer c.move_input_vtable.destroy.?(@ptrCast(instance));
    const encoder = c.colyseus_input_encoder_create(
        @ptrCast(instance), &c.move_input_vtable, true, 3).?;
    defer c.colyseus_input_encoder_free(encoder);

    var out_len: usize = 0;

    instance.*.vx = 1.5;
    instance.*.vy = -2;
    instance.*.jump = true;
    instance.*.action = 3;
    var out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqualSlices(u8, &[_]u8{ 1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3 }, out[0..out_len]);
    try testing.expectEqual(@as(c_int, 1), c.colyseus_input_encoder_seq(encoder));

    instance.*.vx = 2.5;
    out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqualSlices(u8, &[_]u8{ 1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3, 6, 128, 202, 0, 0, 32, 64 }, out[0..out_len]);

    // no change → carry-forward empty slot, ring re-emitted
    out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqualSlices(u8, &[_]u8{ 1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3, 6, 128, 202, 0, 0, 32, 64, 0 }, out[0..out_len]);

    instance.*.vy = 9;
    out = c.colyseus_input_encoder_encode(encoder, &out_len);
    try testing.expectEqualSlices(u8, &[_]u8{ 2, 6, 128, 202, 0, 0, 32, 64, 0, 2, 129, 9 }, out[0..out_len]);
    try testing.expectEqual(@as(c_int, 4), c.colyseus_input_encoder_seq(encoder));
}

// ─── handle framing ─────────────────────────────────────────────────────────

test "handle_reliable_no_stamp" {
    useScriptedNow();
    const ctx = makeHandle(false, false, false, 0);
    defer destroyHandle(ctx);

    ctx.instance.*.vx = 1.5;
    ctx.instance.*.vy = -2;
    ctx.instance.*.jump = true;
    ctx.instance.*.action = 3;
    try testing.expectEqual(@as(c_int, 1), c.colyseus_input_handle_send(ctx.handle));
    ctx.instance.*.vx = 2.5;
    try testing.expectEqual(@as(c_int, 2), c.colyseus_input_handle_send(ctx.handle));
    try testing.expectEqual(@as(c_int, 3), c.colyseus_input_handle_send(ctx.handle)); // body-less [19]

    try testing.expectEqual(@as(c_int, 3), c.colyseus_input_handle_sent_count(ctx.handle));
    try expectFrame(0, &[_]u8{ 19, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3 });
    try expectFrame(1, &[_]u8{ 19, 128, 202, 0, 0, 32, 64 });
    try expectFrame(2, &[_]u8{19});
}

test "handle_reliable_stamped_both" {
    useScriptedNow();
    const clock = makeSyncedClock(); // serverNow(T) = T − 460; smoothedRtt 80
    defer c.colyseus_room_clock_free(clock);
    stub_clock = clock;

    const ctx = makeHandle(false, true, true, 50); // renderDelta = 50+40 = 90
    defer destroyHandle(ctx);

    NOW = 1460; // serverNow = 1000
    ctx.instance.*.vx = 1.5;
    _ = c.colyseus_input_handle_send(ctx.handle);
    NOW = 1476.7; // serverNow = 1016.7 → stamp 1017
    ctx.instance.*.vx = 2;
    _ = c.colyseus_input_handle_send(ctx.handle);
    NOW = 1493.4; // serverNow = 1033.4 → stamp 1033
    _ = c.colyseus_input_handle_send(ctx.handle);

    // [19|0x80][varint Δreckon][uint16 renderDelta=90][delta body]
    try expectFrame(0, &[_]u8{ 147, 205, 232, 3, 90, 0, 128, 202, 0, 0, 192, 63 });
    try expectFrame(1, &[_]u8{ 147, 17, 90, 0, 128, 2 });
    try expectFrame(2, &[_]u8{ 147, 16, 90, 0 });

    try testing.expectEqual(@as(f64, 1000), c.colyseus_input_handle_reckon_time_at(ctx.handle, 1));
    try testing.expectEqual(@as(f64, 1017), c.colyseus_input_handle_reckon_time_at(ctx.handle, 2));
    try testing.expectEqual(@as(f64, 1033), c.colyseus_input_handle_reckon_time_at(ctx.handle, 3));
}

test "handle_reliable_stamped_render_only" {
    useScriptedNow();
    const clock = makeSyncedClock();
    defer c.colyseus_room_clock_free(clock);
    stub_clock = clock;

    const ctx = makeHandle(false, true, false, 50);
    defer destroyHandle(ctx);

    NOW = 1460; // serverNow = 1000 → stamp = 1000-90 = 910
    ctx.instance.*.vx = 1.5;
    _ = c.colyseus_input_handle_send(ctx.handle);
    NOW = 1510; // serverNow = 1050 → stamp 960, Δ = 50
    ctx.instance.*.vx = 2;
    _ = c.colyseus_input_handle_send(ctx.handle);

    try expectFrame(0, &[_]u8{ 147, 205, 142, 3, 128, 202, 0, 0, 192, 63 });
    try expectFrame(1, &[_]u8{ 147, 50, 128, 2 });
    try testing.expectEqual(@as(f64, 0), c.colyseus_input_handle_reckon_time_at(ctx.handle, 1)); // reckon ring off
}

test "handle_unstamped_before_sync" {
    useScriptedNow();
    const clock = c.colyseus_room_clock_create(); // never sampled → not synced
    defer c.colyseus_room_clock_free(clock);
    stub_clock = clock;

    const ctx = makeHandle(false, true, true, 0);
    defer destroyHandle(ctx);

    ctx.instance.*.vx = 1;
    _ = c.colyseus_input_handle_send(ctx.handle);
    try expectFrame(0, &[_]u8{ 147, 0, 0, 0, 128, 1 });
}

test "handle_unreliable" {
    useScriptedNow();
    const clock = makeSyncedClock();
    defer c.colyseus_room_clock_free(clock);
    stub_clock = clock;

    const ctx = makeHandle(true, false, true, 0);
    defer destroyHandle(ctx);

    ctx.instance.*.vx = 1.5;
    try testing.expectEqual(@as(c_int, 1), c.colyseus_input_handle_send(ctx.handle));
    ctx.instance.*.vx = 2.5;
    try testing.expectEqual(@as(c_int, 2), c.colyseus_input_handle_send(ctx.handle));
    try testing.expectEqual(@as(c_int, 2), c.colyseus_input_handle_sent_count(ctx.handle));

    // [20][baseSeq][len][slot]… — unreliable is never stamped
    try expectFrame(0, &[_]u8{ 20, 1, 6, 128, 202, 0, 0, 192, 63 });
    try expectFrame(1, &[_]u8{ 20, 1, 6, 128, 202, 0, 0, 192, 63, 6, 128, 202, 0, 0, 32, 64 });
}

test "handle_ack_rtt" {
    useScriptedNow();
    stub_clock = null;
    const ctx = makeHandle(false, false, false, 0);
    defer destroyHandle(ctx);

    NOW = 1000;
    ctx.instance.*.vx = 1;
    _ = c.colyseus_input_handle_send(ctx.handle);
    NOW = 1016;
    ctx.instance.*.vx = 2;
    _ = c.colyseus_input_handle_send(ctx.handle);
    NOW = 1033;
    ctx.instance.*.vx = 3;
    _ = c.colyseus_input_handle_send(ctx.handle);

    NOW = 1080;
    try testing.expectEqual(@as(f64, 80), c.colyseus_input_handle_ack_input(ctx.handle, 1));
    try testing.expectEqual(@as(f64, -1), c.colyseus_input_handle_ack_input(ctx.handle, 1)); // stale
    NOW = 1120;
    try testing.expectEqual(@as(f64, 87), c.colyseus_input_handle_ack_input(ctx.handle, 3)); // skips 2
    try testing.expectEqual(@as(c_int, 3), c.colyseus_input_handle_last_processed(ctx.handle));
    try testing.expectEqual(@as(c_int, 0), c.colyseus_input_handle_pending_count(ctx.handle));

    // replay ring: pending inputs readable until acked
    NOW = 1200;
    ctx.instance.*.vx = 4;
    _ = c.colyseus_input_handle_send(ctx.handle); // seq 4
    const buffered: *c.move_input_t = @ptrCast(@alignCast(c.colyseus_input_handle_at(ctx.handle, 4).?));
    try testing.expectEqual(@as(f64, 4), buffered.vx);
    try testing.expectEqual(@as(?*c.colyseus_schema_t, null), c.colyseus_input_handle_at(ctx.handle, 3)); // acked → gone

    // reset: epoch++, fresh counters, next send = full snapshot
    const epoch_before = c.colyseus_input_handle_epoch(ctx.handle);
    c.colyseus_input_handle_reset(ctx.handle);
    try testing.expectEqual(epoch_before + 1, c.colyseus_input_handle_epoch(ctx.handle));
    try testing.expectEqual(@as(c_int, 0), c.colyseus_input_handle_sent_count(ctx.handle));
    NOW = 1300;
    ctx.instance.*.vx = 5;
    try testing.expectEqual(@as(c_int, 1), c.colyseus_input_handle_send(ctx.handle));
    try expectFrame(sent_count - 1, &[_]u8{ 19, 128, 5, 129, 0, 130, 0, 131, 0 });
    NOW = 1360;
    try testing.expectEqual(@as(f64, 60), c.colyseus_input_handle_ack_input(ctx.handle, 1));
}

// ─── clock math ─────────────────────────────────────────────────────────────

test "clock_samples" {
    useScriptedNow();
    const clock = c.colyseus_room_clock_create().?;
    defer c.colyseus_room_clock_free(clock);
    c.colyseus_room_clock_set_patch_interval(clock, 50);

    // (tNow, sNow, rtt) → (offset, rtt, smoothedRtt, jitter, lastServerTime)
    const script = [_][8]f64{
        .{ 1000, 500, -1, -500, 0, 0, 0, 500 },
        .{ 1050, 550, 80, -496, 80, 80, 0, 550 },
        .{ 1100, 600, 84, -492.20000000000005, 84, 80.4, 0, 600 },
        .{ 1155, 655, 90, -488.4800000000001, 90, 81.36000000000001, 0.3125, 655 },
        .{ 1205, 705, 76, -485.83200000000005, 76, 80.82400000000001, 0.29296875, 705 },
        .{ 1305, 805, 82, -483.14880000000005, 82, 80.94160000000002, 0.274658203125, 805 },
        .{ 1655, 1155, 78, -480.93392000000006, 78, 80.64744000000002, 0.274658203125, 1155 },
        .{ 1705, 1205, 400, -480.93392000000006, 78, 80.64744000000002, 0.2574920654296875, 1205 },
        .{ 1755, 1255, 74, -479.1405280000001, 74, 79.98269600000002, 0.24139881134033203, 1255 },
    };
    for (script) |row| {
        NOW = row[0];
        c.colyseus_room_clock_sample(clock, row[1], row[2]);
        try testing.expectEqual(row[3], c.colyseus_room_clock_offset(clock));
        try testing.expectEqual(row[4], c.colyseus_room_clock_rtt(clock));
        try testing.expectEqual(row[5], c.colyseus_room_clock_smoothed_rtt(clock));
        try testing.expectEqual(row[6], c.colyseus_room_clock_jitter(clock));
        try testing.expectEqual(row[7], c.colyseus_room_clock_last_server_time(clock));
    }

    NOW = 1800;
    try testing.expectEqual(@as(f64, 1320.8594719999999), c.colyseus_room_clock_server_now(clock));

    // render_now — 1e-6 tolerance (exp() ULP variance across libms)
    NOW = 1800;
    const r1 = c.colyseus_room_clock_render_now(clock);
    NOW = 1816;
    const r2 = c.colyseus_room_clock_render_now(clock);
    NOW = 1816.2;
    const r3 = c.colyseus_room_clock_render_now(clock); // same frame → unchanged
    try testing.expect(@abs(r1 - 1320.8594719999999) < 1e-6);
    try testing.expect(@abs(r2 - 1336.8594719999999) < 1e-6);
    try testing.expectEqual(r2, r3);

    // reset clears estimates; patch interval is config and survives
    c.colyseus_room_clock_reset(clock);
    try testing.expectEqual(@as(f64, 0), c.colyseus_room_clock_smoothed_rtt(clock));
    try testing.expectEqual(@as(f64, 0), c.colyseus_room_clock_last_server_time(clock));
    try testing.expectEqual(@as(f64, 50), c.colyseus_room_clock_patch_interval(clock));
}

test "clock_gate_warmup" {
    useScriptedNow();
    const clock = c.colyseus_room_clock_create().?;
    defer c.colyseus_room_clock_free(clock);
    c.colyseus_room_clock_set_patch_interval(clock, 50);

    var t_now: f64 = 1000;
    var i: usize = 1;
    while (i <= 35) : (i += 1) {
        t_now += 50;
        NOW = t_now;
        const rtt: f64 = if (i % 2 == 0) 200 else 100;
        c.colyseus_room_clock_sample(clock, t_now - 400, rtt);
        switch (i) {
            5 => try testing.expectEqual(@as(f64, -341.855), c.colyseus_room_clock_offset(clock)),
            10 => try testing.expectEqual(@as(f64, -332.85995895), c.colyseus_room_clock_offset(clock)),
            20 => try testing.expectEqual(@as(f64, -326.88359617343616), c.colyseus_room_clock_offset(clock)),
            30 => try testing.expectEqual(@as(f64, -324.79976732303214), c.colyseus_room_clock_offset(clock)),
            35 => try testing.expectEqual(@as(f64, -331.6290303784904), c.colyseus_room_clock_offset(clock)),
            else => {},
        }
    }
    try testing.expectEqual(@as(f64, 146.0509707868457), c.colyseus_room_clock_smoothed_rtt(clock));
}

// ─── room-level: sections + TIMED routing + reflection-synthesized input ────

var room_sent_frames: [8][64]u8 = undefined;
var room_sent_lens: [8]usize = undefined;
var room_sent_count: usize = 0;

fn roomStubSend(transport: [*c]c.colyseus_transport_t, data: [*c]const u8, length: usize) callconv(.c) void {
    _ = transport;
    if (room_sent_count < room_sent_frames.len and length <= 64) {
        @memcpy(room_sent_frames[room_sent_count][0..length], data[0..length]);
        room_sent_lens[room_sent_count] = length;
        room_sent_count += 1;
    }
}

fn roomStubIsOpen(transport: [*c]const c.colyseus_transport_t) callconv(.c) bool {
    _ = transport;
    return true;
}

var room_stub_transport = std.mem.zeroInit(c.colyseus_transport_t, .{});

test "room_input_options_and_timed_routing" {
    useScriptedNow();
    room_sent_count = 0;
    room_stub_transport.send = roomStubSend;
    room_stub_transport.is_open = roomStubIsOpen;

    const room = c.colyseus_room_create("phase0", null).?;
    c.colyseus_room_set_state_type(room, &c.p0_state_vtable);
    room.*.transport = &room_stub_transport;
    defer {
        room.*.transport = null; // the stub is not heap-allocated
        c.colyseus_room_free(room);
    }

    // JOIN_ROOM fixture with INPUT_REFLECTION + INPUT_OPTIONS sections
    // (flags FIXED|PATCH|SUB, tickRate 20, patchRate 50, subSteps 2) —
    // from PORTING/generate-phase0-fixtures.cts.
    const join = [_]u8{ 10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2 };
    c.colyseus_room_process_message(room, &join, join.len);

    const clock = c.colyseus_room_get_clock(room).?;
    try testing.expectEqual(@as(f64, 50), c.colyseus_room_clock_patch_interval(clock));

    // no explicit vtable: the input schema is synthesized from INPUT_REFLECTION
    const handle = c.colyseus_room_input(room, null, null).?;
    try testing.expectEqual(@as(c_int, 20), c.colyseus_input_handle_tick_rate(handle));
    try testing.expectEqual(@as(c_int, 50), c.colyseus_input_handle_patch_rate(handle));
    try testing.expectEqual(@as(c_int, 2), c.colyseus_input_handle_sub_steps(handle));
    try testing.expect(c.colyseus_input_handle_replay_buffer_size(handle) >= 64);

    // same handle on later calls
    try testing.expectEqual(handle, c.colyseus_room_input(room, null, null).?);

    // the synthesized input schema has the server's fields (x, y)
    const data: *c.colyseus_dynamic_schema_t = @ptrCast(@alignCast(c.colyseus_input_handle_data(handle)));
    // set() takes ownership — allocate through the value API
    const x_value = c.colyseus_dynamic_value_create(c.COLYSEUS_FIELD_NUMBER);
    x_value.*.data.num = 4.5;
    c.colyseus_dynamic_schema_set(data, 0, "x", x_value);
    const y_value = c.colyseus_dynamic_value_create(c.COLYSEUS_FIELD_NUMBER);
    y_value.*.data.num = 2;
    c.colyseus_dynamic_schema_set(data, 1, "y", y_value);

    const frames_before = room_sent_count;
    try testing.expectEqual(@as(c_int, 1), c.colyseus_input_handle_send(handle));
    try testing.expectEqual(frames_before + 1, room_sent_count);
    try testing.expectEqualSlices(u8, &[_]u8{ 19, 128, 202, 0, 0, 144, 64, 129, 2 },
        room_sent_frames[room_sent_count - 1][0..room_sent_lens[room_sent_count - 1]]);

    // TIMED heartbeat patch [15|0x80][u32 sNow=750][u32 inputSeq=0]
    const heartbeat = [_]u8{ 143, 238, 2, 0, 0, 0, 0, 0, 0 };
    c.colyseus_room_process_message(room, &heartbeat, heartbeat.len);
    try testing.expectEqual(@as(f64, 750), c.colyseus_room_clock_last_server_time(clock));
}
