const std = @import("std");
const testing = std.testing;

// ============================================================================
// ArraySchema wire-semantics tests (schema 5.0, 0.18 line)
//
// Byte fixtures generated by schema-5.0
// test-external/generate-arrayschema-fixtures.ts — each fixture is
// self-verified against the 5.0 JS Decoder before being printed.
// See schema-5.0 TODO/sdk-decoders-arrayschema-insert.md.
//
// Covers:
//   - "ADD at occupied index = insert" (schema#219)
//   - DELETE_BY_REFID idempotency guards + ref-count decrement (schema#220)
//   - MOVE (32) / MOVE_AND_ADD (160) opcode handling
//   - decode-end hole compaction renumbers survivors 0..n-1
// ============================================================================

const c = @cImport({
    @cInclude("colyseus/schema/types.h");
    @cInclude("colyseus/schema/collections.h");
    @cInclude("colyseus/schema/ref_tracker.h");
    @cInclude("colyseus/schema/decoder.h");
    @cInclude("schema/array_schema_insert_ops.h");
});

// ============================================================================
// Helpers
// ============================================================================

fn createDecoder() *c.colyseus_decoder_t {
    return c.colyseus_decoder_create(&c.array_schema_insert_ops_vtable).?;
}

fn getState(decoder: *c.colyseus_decoder_t) *c.array_schema_insert_ops_t {
    return @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
}

fn decode(decoder: *c.colyseus_decoder_t, bytes: []const u8) void {
    var it = c.colyseus_iterator_t{ .offset = 0 };
    c.colyseus_decoder_decode(decoder, bytes.ptr, bytes.len, &it);
}

fn numAt(arr: *c.colyseus_array_schema_t, index: c_int) f64 {
    const ptr = c.colyseus_array_schema_get(arr, index);
    const v: *f64 = @ptrCast(@alignCast(ptr.?));
    return v.*;
}

fn itemValueAt(arr: *c.colyseus_array_schema_t, index: c_int) f64 {
    const ptr = c.colyseus_array_schema_get(arr, index);
    const item: *c.item_t = @ptrCast(@alignCast(ptr.?));
    return item.value;
}

fn playerNameAt(arr: *c.colyseus_array_schema_t, index: c_int) []const u8 {
    const ptr = c.colyseus_array_schema_get(arr, index);
    const player: *c.player_t = @ptrCast(@alignCast(ptr.?));
    return std.mem.span(player.name);
}

const snapshot_numbers = [_]u8{ 128, 1, 129, 2, 130, 3, 255, 1, 128, 0, 1, 128, 1, 2, 128, 2, 3 };

// ============================================================================
// "ADD at occupied index = insert"
// ============================================================================

test "arrayschema_unshift_consecutive" {
    // [1,2,3] -> unshift(0); unshift(-1) => [-1, 0, 1, 2, 3]
    const decoder = createDecoder();
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &snapshot_numbers);
    decode(decoder, &[_]u8{ 255, 1, 128, 0, 255, 128, 1, 0 });

    const numbers: *c.colyseus_array_schema_t = getState(decoder).numbers.?;
    try testing.expectEqual(@as(c_int, 5), numbers.count);
    try testing.expectEqual(@as(f64, -1), numAt(numbers, 0));
    try testing.expectEqual(@as(f64, 0), numAt(numbers, 1));
    try testing.expectEqual(@as(f64, 1), numAt(numbers, 2));
    try testing.expectEqual(@as(f64, 2), numAt(numbers, 3));
    try testing.expectEqual(@as(f64, 3), numAt(numbers, 4));
}

test "arrayschema_unshift_multi" {
    // [1,2,3] -> unshift(-1, -2) => [-1, -2, 1, 2, 3]
    const decoder = createDecoder();
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &snapshot_numbers);
    decode(decoder, &[_]u8{ 255, 1, 128, 0, 255, 128, 1, 254 });

    const numbers: *c.colyseus_array_schema_t = getState(decoder).numbers.?;
    try testing.expectEqual(@as(c_int, 5), numbers.count);
    try testing.expectEqual(@as(f64, -1), numAt(numbers, 0));
    try testing.expectEqual(@as(f64, -2), numAt(numbers, 1));
    try testing.expectEqual(@as(f64, 1), numAt(numbers, 2));
    try testing.expectEqual(@as(f64, 2), numAt(numbers, 3));
    try testing.expectEqual(@as(f64, 3), numAt(numbers, 4));
}

test "arrayschema_unshift_same_tick_ops" {
    // [1,2,3] -> arr[2]=99; push(4); unshift(0) => [0, 1, 2, 99, 4]
    const decoder = createDecoder();
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &snapshot_numbers);
    decode(decoder, &[_]u8{ 255, 1, 128, 0, 0, 0, 3, 99, 128, 4, 4 });

    const numbers: *c.colyseus_array_schema_t = getState(decoder).numbers.?;
    try testing.expectEqual(@as(c_int, 5), numbers.count);
    try testing.expectEqual(@as(f64, 0), numAt(numbers, 0));
    try testing.expectEqual(@as(f64, 1), numAt(numbers, 1));
    try testing.expectEqual(@as(f64, 2), numAt(numbers, 2));
    try testing.expectEqual(@as(f64, 99), numAt(numbers, 3));
    try testing.expectEqual(@as(f64, 4), numAt(numbers, 4));
}

test "arrayschema_clear_unshift_same_tick" {
    // [1,2,3] -> clear(); unshift(9); unshift(8) => [8, 9]
    const decoder = createDecoder();
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &snapshot_numbers);
    decode(decoder, &[_]u8{ 255, 1, 10, 128, 0, 8, 128, 1, 9 });

    const numbers: *c.colyseus_array_schema_t = getState(decoder).numbers.?;
    try testing.expectEqual(@as(c_int, 2), numbers.count);
    try testing.expectEqual(@as(f64, 8), numAt(numbers, 0));
    try testing.expectEqual(@as(f64, 9), numAt(numbers, 1));
}

test "arrayschema_unshift_schema_instances" {
    // [Item(1), Item(2)] -> unshift(Item(0)); unshift(Item(-1))
    const decoder = createDecoder();
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 130, 3, 255, 2, 128, 0, 4, 128, 1, 5, 255, 4, 128, 1, 255, 5, 128, 2 });
    decode(decoder, &[_]u8{ 255, 2, 128, 0, 7, 128, 1, 6, 255, 6, 128, 0, 255, 7, 128, 255 });

    const items: *c.colyseus_array_schema_t = getState(decoder).items.?;
    try testing.expectEqual(@as(c_int, 4), items.count);
    try testing.expectEqual(@as(f64, -1), itemValueAt(items, 0));
    try testing.expectEqual(@as(f64, 0), itemValueAt(items, 1));
    try testing.expectEqual(@as(f64, 1), itemValueAt(items, 2));
    try testing.expectEqual(@as(f64, 2), itemValueAt(items, 3));

    // no refId leaks: state, numbers, items, players + 4 Item children
    try testing.expectEqual(@as(usize, 8), c.colyseus_ref_tracker_count(decoder.refs));
}

// ============================================================================
// sort() must NOT insert (REPLACE at occupied indexes, incl. index 0)
// ============================================================================

test "arrayschema_sort_no_insert" {
    const decoder = createDecoder();
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 128, 2, 6, 128, 3, 7, 128, 4, 8, 255, 4, 128, 163, 79, 110, 101, 129, 10, 130, 0, 255, 5, 128, 163, 84, 119, 111, 129, 30, 130, 1, 255, 6, 128, 165, 84, 104, 114, 101, 101, 129, 20, 130, 2, 255, 7, 128, 164, 70, 111, 117, 114, 129, 50, 130, 3, 255, 8, 128, 164, 70, 105, 118, 101, 129, 40, 130, 4 });

    const players: *c.colyseus_array_schema_t = getState(decoder).players.?;
    try testing.expectEqual(@as(c_int, 5), players.count);
    try testing.expectEqualStrings("One", playerNameAt(players, 0));
    try testing.expectEqualStrings("Five", playerNameAt(players, 4));

    // sort by y desc => [Five, Four, Three, Two, One], length stays 5
    decode(decoder, &[_]u8{ 255, 3, 0, 0, 8, 0, 1, 7, 0, 2, 6, 0, 3, 5, 0, 4, 4 });
    try testing.expectEqual(@as(c_int, 5), players.count);
    try testing.expectEqualStrings("Five", playerNameAt(players, 0));
    try testing.expectEqualStrings("Four", playerNameAt(players, 1));
    try testing.expectEqualStrings("Three", playerNameAt(players, 2));
    try testing.expectEqualStrings("Two", playerNameAt(players, 3));
    try testing.expectEqualStrings("One", playerNameAt(players, 4));

    // sort by x => [One, Three, Two, Five, Four], length stays 5
    decode(decoder, &[_]u8{ 255, 3, 0, 0, 4, 0, 1, 6, 0, 2, 5, 0, 3, 8, 0, 4, 7 });
    try testing.expectEqual(@as(c_int, 5), players.count);
    try testing.expectEqualStrings("One", playerNameAt(players, 0));
    try testing.expectEqualStrings("Three", playerNameAt(players, 1));
    try testing.expectEqualStrings("Two", playerNameAt(players, 2));
    try testing.expectEqualStrings("Five", playerNameAt(players, 3));
    try testing.expectEqualStrings("Four", playerNameAt(players, 4));
}

// ============================================================================
// DELETE_BY_REFID idempotency (mid-tick join)
// ============================================================================

test "arrayschema_stale_delete_by_refid" {
    // The same shared patch is decoded by an old client (knows all refIds)
    // and a fresh client (bootstrapped mid-tick, only knows the survivors).
    // Stale DELETE_BY_REFIDs must be skipped silently.
    const shared_patch = [_]u8{ 255, 2, 33, 4, 33, 5, 33, 6 };

    const old_decoder = createDecoder();
    defer c.colyseus_decoder_free(old_decoder);
    decode(old_decoder, &[_]u8{ 128, 1, 129, 2, 130, 3, 255, 2, 128, 0, 4, 128, 1, 5, 128, 2, 6, 128, 3, 7, 128, 4, 8, 255, 4, 128, 0, 255, 5, 128, 1, 255, 6, 128, 2, 255, 7, 128, 3, 255, 8, 128, 4 });

    const fresh_decoder = createDecoder();
    defer c.colyseus_decoder_free(fresh_decoder);
    decode(fresh_decoder, &[_]u8{ 128, 1, 129, 2, 130, 3, 255, 2, 128, 0, 6, 128, 1, 7, 128, 2, 8, 255, 6, 128, 2, 255, 7, 128, 3, 255, 8, 128, 4 });

    decode(old_decoder, &shared_patch);
    decode(fresh_decoder, &shared_patch);

    // both converge to the server state: [3, 4] at dense indexes 0..1
    const old_items: *c.colyseus_array_schema_t = getState(old_decoder).items.?;
    try testing.expectEqual(@as(c_int, 2), old_items.count);
    try testing.expectEqual(@as(f64, 3), itemValueAt(old_items, 0));
    try testing.expectEqual(@as(f64, 4), itemValueAt(old_items, 1));

    const fresh_items: *c.colyseus_array_schema_t = getState(fresh_decoder).items.?;
    try testing.expectEqual(@as(c_int, 2), fresh_items.count);
    try testing.expectEqual(@as(f64, 3), itemValueAt(fresh_items, 0));
    try testing.expectEqual(@as(f64, 4), itemValueAt(fresh_items, 1));

    // ref counts converge: state + 3 collections + 2 surviving Items
    try testing.expectEqual(@as(usize, 6), c.colyseus_ref_tracker_count(old_decoder.refs));
    try testing.expectEqual(@as(usize, 6), c.colyseus_ref_tracker_count(fresh_decoder.refs));
}

// ============================================================================
// MOVE (32) / MOVE_AND_ADD (160)
// ============================================================================

test "arrayschema_move" {
    const decoder = createDecoder();
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 130, 3, 255, 2, 128, 0, 4, 128, 1, 5, 128, 2, 6, 255, 4, 128, 1, 255, 5, 128, 2, 255, 6, 128, 3 });

    // move(): swap arr[0] <-> arr[1] — carries MOVE (32) ops => [2, 1, 3]
    decode(decoder, &[_]u8{ 255, 2, 32, 0, 5, 32, 1, 4, 255, 4, 128, 1 });
    const items: *c.colyseus_array_schema_t = getState(decoder).items.?;
    try testing.expectEqual(@as(c_int, 3), items.count);
    try testing.expectEqual(@as(f64, 2), itemValueAt(items, 0));
    try testing.expectEqual(@as(f64, 1), itemValueAt(items, 1));
    try testing.expectEqual(@as(f64, 3), itemValueAt(items, 2));

    // move(): new Item(9) at occupied slot 2 — MOVE_AND_ADD (160) => [2, 1, 9]
    decode(decoder, &[_]u8{ 255, 2, 160, 2, 7, 255, 7, 128, 9 });
    try testing.expectEqual(@as(c_int, 3), items.count);
    try testing.expectEqual(@as(f64, 2), itemValueAt(items, 0));
    try testing.expectEqual(@as(f64, 1), itemValueAt(items, 1));
    try testing.expectEqual(@as(f64, 9), itemValueAt(items, 2));
}
