const std = @import("std");
const testing = std.testing;

// ============================================================================
// decodeResync tests (full-snapshot reconciliation, schema 5.0.8 port)
//
// Byte fixtures generated by schema-5.0
// test-external/generate-resync-fixtures.ts — each fixture is self-verified
// against the 5.0 JS Decoder before being printed.
// Contract: PORTING_RESYNC.md / test/ResyncSweep.test.ts.
// ============================================================================

const c = @cImport({
    @cInclude("colyseus/schema/types.h");
    @cInclude("colyseus/schema/collections.h");
    @cInclude("colyseus/schema/ref_tracker.h");
    @cInclude("colyseus/schema/decoder.h");
    @cInclude("schema/resync_state.h");
    @cInclude("schema/resync_array_state.h");
    @cInclude("schema/resync_state_v1.h");
    @cInclude("schema/resync_transient_state.h");
});

// ============================================================================
// Helpers
// ============================================================================

fn decode(decoder: *c.colyseus_decoder_t, bytes: []const u8) void {
    var it = c.colyseus_iterator_t{ .offset = 0 };
    c.colyseus_decoder_decode(decoder, bytes.ptr, bytes.len, &it);
}

fn decodeResync(decoder: *c.colyseus_decoder_t, bytes: []const u8) void {
    var it = c.colyseus_iterator_t{ .offset = 0 };
    c.colyseus_decoder_decode_resync(decoder, bytes.ptr, bytes.len, &it);
}

fn unitAt(map: [*c]c.colyseus_map_schema_t, key: [*c]const u8) ?*c.unit_t {
    const ptr = c.colyseus_map_schema_get(map, key);
    if (ptr == null) return null;
    return @ptrCast(@alignCast(ptr));
}

fn treeAt(map: [*c]c.colyseus_map_schema_t, key: [*c]const u8) ?f64 {
    const ptr = c.colyseus_map_schema_get(map, key);
    if (ptr == null) return null;
    const v: *f64 = @ptrCast(@alignCast(ptr));
    return v.*;
}

fn gemPriceAt(arr: [*c]c.colyseus_array_schema_t, index: c_int) f64 {
    const gem: *c.gem_t = @ptrCast(@alignCast(c.colyseus_array_schema_get(arr, index).?));
    return gem.price;
}

fn refsCount(decoder: *c.colyseus_decoder_t) usize {
    return c.colyseus_ref_tracker_count(decoder.refs);
}

// ============================================================================
// scenarios
// ============================================================================

test "resync_ghost_map" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 128, 1, 162, 101, 50, 5, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4, 255, 5, 128, 163, 116, 119, 111, 129, 100, 130, 6 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    try testing.expectEqual(@as(c_int, 2), state.units.*.count);

    // offline: e2 died; its DELETE patch was never delivered
    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4 });

    try testing.expectEqual(@as(c_int, 1), state.units.*.count);
    try testing.expect(unitAt(state.units, "e1") != null);
    try testing.expect(unitAt(state.units, "e2") == null);
    try testing.expectEqual(@as(usize, 5), refsCount(decoder));
}

test "resync_prune_primitive_map" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 2, 128, 0, 162, 116, 49, 10, 128, 1, 162, 116, 50, 20, 128, 2, 162, 116, 51, 30 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    try testing.expectEqual(@as(c_int, 3), state.trees.*.count);

    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 2, 128, 0, 162, 116, 49, 10, 128, 2, 162, 116, 51, 30 });

    try testing.expectEqual(@as(c_int, 2), state.trees.*.count);
    try testing.expectEqual(@as(f64, 10), treeAt(state.trees, "t1").?);
    try testing.expect(treeAt(state.trees, "t2") == null);
    try testing.expectEqual(@as(f64, 30), treeAt(state.trees, "t3").?);
}

test "resync_nested_collection" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 164, 104, 101, 114, 111, 3, 255, 3, 128, 164, 104, 101, 114, 111, 129, 100, 130, 4, 255, 4, 128, 0, 5, 128, 1, 6, 128, 2, 7, 255, 5, 128, 0, 255, 6, 128, 1, 255, 7, 128, 2 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    const hero_before = unitAt(state.units, "hero").?;

    // offline: hero lost the middle gem
    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 164, 104, 101, 114, 111, 3, 255, 3, 128, 164, 104, 101, 114, 111, 129, 100, 130, 4, 255, 4, 128, 0, 5, 128, 1, 7, 255, 5, 128, 0, 255, 7, 128, 2 });

    const hero_after = unitAt(state.units, "hero").?;
    try testing.expectEqual(hero_before, hero_after); // retained parent keeps identity
    try testing.expectEqual(@as(c_int, 2), hero_after.gems.*.count);
    try testing.expectEqual(@as(f64, 0), gemPriceAt(hero_after.gems, 0));
    try testing.expectEqual(@as(f64, 2), gemPriceAt(hero_after.gems, 1));
}

test "resync_view_interior" {
    // snapshots are view-encoded (ADD_BY_REFID ops)
    const decoder = c.colyseus_decoder_create(&c.resync_array_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 255, 0, 128, 1, 255, 1, 129, 2, 2, 129, 4, 4, 129, 6, 6, 255, 2, 128, 161, 97, 129, 100, 130, 3, 255, 4, 128, 161, 98, 129, 100, 130, 5, 255, 6, 128, 161, 99, 129, 100, 130, 7 });

    const state: *c.resync_array_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    try testing.expectEqual(@as(c_int, 3), state.arr.*.count);

    // offline: b left the view — an interior index, not the tail
    decodeResync(decoder, &[_]u8{ 255, 0, 128, 1, 255, 1, 129, 2, 2, 129, 6, 6, 255, 2, 128, 161, 97, 129, 100, 130, 3, 255, 6, 128, 161, 99, 129, 100, 130, 7 });

    try testing.expectEqual(@as(c_int, 2), state.arr.*.count);
    const first: *c.unit_t = @ptrCast(@alignCast(c.colyseus_array_schema_get(state.arr, 0).?));
    const second: *c.unit_t = @ptrCast(@alignCast(c.colyseus_array_schema_get(state.arr, 1).?));
    try testing.expectEqualStrings("a", std.mem.span(first.name));
    try testing.expectEqualStrings("c", std.mem.span(second.name));
}

test "resync_emptied_collection" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 128, 1, 162, 101, 50, 5, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4, 255, 5, 128, 163, 116, 119, 111, 129, 100, 130, 6 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));

    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2 });

    try testing.expectEqual(@as(c_int, 0), state.units.*.count);
}

test "resync_no_double_decrement" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 164, 114, 105, 99, 104, 3, 128, 1, 164, 107, 101, 101, 112, 10, 255, 3, 128, 164, 114, 105, 99, 104, 129, 100, 130, 4, 255, 4, 128, 0, 5, 128, 1, 6, 128, 2, 7, 128, 3, 8, 128, 4, 9, 255, 5, 128, 0, 255, 6, 128, 1, 255, 7, 128, 2, 255, 8, 128, 3, 255, 9, 128, 4, 255, 10, 128, 164, 107, 101, 101, 112, 129, 100, 130, 11, 255, 11, 128, 0, 12, 128, 1, 13, 255, 12, 128, 0, 255, 13, 128, 1 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));

    // offline: 'rich' (5 nested gems) died — GC must release the subtree exactly once
    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 1, 164, 107, 101, 101, 112, 10, 255, 10, 128, 164, 107, 101, 101, 112, 129, 100, 130, 11, 255, 11, 128, 0, 12, 128, 1, 13, 255, 12, 128, 0, 255, 13, 128, 1 });

    try testing.expectEqual(@as(c_int, 1), state.units.*.count);
    try testing.expectEqual(@as(c_int, 2), unitAt(state.units, "keep").?.gems.*.count);
    try testing.expectEqual(@as(usize, 7), refsCount(decoder));
}

test "resync_late_delete" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 128, 1, 162, 101, 50, 5, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4, 255, 5, 128, 163, 116, 119, 111, 129, 100, 130, 6 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));

    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4 });
    try testing.expectEqual(@as(c_int, 1), state.units.*.count);

    // the DELETE patch encoded before the resync arrives late — tolerated
    decode(decoder, &[_]u8{ 255, 1, 64, 1 });

    try testing.expectEqual(@as(c_int, 1), state.units.*.count);
    try testing.expect(unitAt(state.units, "e1") != null);
}

test "resync_survivor_identity" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 128, 1, 164, 103, 111, 110, 101, 5, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4, 255, 5, 128, 164, 103, 111, 110, 101, 129, 100, 130, 6 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    const survivor = unitAt(state.units, "e1").?;

    // offline: survivor's hp changed to 55, sibling died
    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 255, 3, 128, 163, 111, 110, 101, 129, 55, 130, 4 });

    const after = unitAt(state.units, "e1").?;
    try testing.expectEqual(survivor, after); // same instance across resync
    try testing.expectEqual(@as(f64, 55), after.hp);
    try testing.expectEqual(@as(c_int, 1), state.units.*.count);

    // live patches keep working after the resync
    decode(decoder, &[_]u8{ 255, 3, 129, 77 });
    try testing.expectEqual(@as(f64, 77), after.hp);
}

test "resync_rekey" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 163, 111, 108, 100, 3, 255, 3, 128, 165, 109, 111, 118, 101, 114, 129, 100, 130, 4 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    const instance = unitAt(state.units, "old").?;

    // offline: the same server instance moved to a new key
    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 1, 163, 110, 101, 119, 3, 255, 3, 128, 165, 109, 111, 118, 101, 114, 129, 100, 130, 4 });

    try testing.expectEqual(instance, unitAt(state.units, "new").?); // same instance, new key
    try testing.expect(unitAt(state.units, "old") == null);
    try testing.expectEqual(@as(c_int, 1), state.units.*.count);
    try testing.expectEqual(@as(usize, 5), refsCount(decoder));
}

test "resync_replace_same_key" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 161, 107, 3, 255, 3, 128, 165, 102, 105, 114, 115, 116, 129, 100, 130, 4, 255, 4, 128, 0, 5, 128, 1, 6, 255, 5, 128, 0, 255, 6, 128, 1 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    const old_instance = unitAt(state.units, "k").?;
    const old_ref_id = old_instance.__base.__refId;

    // offline: the entity at "k" died and a NEW one spawned at the same key
    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 1, 161, 107, 7, 255, 7, 128, 166, 115, 101, 99, 111, 110, 100, 129, 100, 130, 8 });

    const replacement = unitAt(state.units, "k").?;
    try testing.expectEqualStrings("second", std.mem.span(replacement.name));
    try testing.expect(replacement != old_instance); // fresh instance
    try testing.expect(!c.colyseus_ref_tracker_has(decoder.*.refs, old_ref_id)); // old ref GC'd
    try testing.expectEqual(@as(usize, 5), refsCount(decoder));
}

test "resync_damaged" {
    // version skew: the resync payload comes from a server whose Player has
    // an extra field → schema-mismatch skip → damage flag → sweep ABORTED
    // (keeping a ghost beats deleting live entries on bad data)
    const decoder = c.colyseus_decoder_create(&c.resync_state_v1_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 255, 1, 128, 0, 162, 112, 49, 2, 128, 1, 162, 112, 50, 3, 255, 2, 128, 1, 255, 3, 128, 2 });

    const state: *c.resync_state_v1_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    try testing.expectEqual(@as(c_int, 2), state.players.*.count);

    decodeResync(decoder, &[_]u8{ 128, 1, 255, 1, 128, 0, 162, 112, 49, 2, 255, 2, 128, 1, 129, 162, 104, 105 });

    try testing.expectEqual(@as(c_int, 2), state.players.*.count); // ghost p2 retained, no crash
}

test "resync_transient" {
    const decoder = c.colyseus_decoder_create(&c.resync_transient_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 255, 1, 128, 0, 162, 101, 49, 3, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4 });
    // transient entries arrive via patch only — never via full snapshots
    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 255, 2, 128, 0, 162, 108, 49, 1, 128, 1, 162, 108, 50, 2, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4 });

    const state: *c.resync_transient_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    try testing.expectEqual(@as(c_int, 2), state.locals.*.count);

    // the resync snapshot never mentions locals → presence rule leaves it alone
    decodeResync(decoder, &[_]u8{ 128, 1, 255, 1, 128, 0, 162, 101, 49, 3, 128, 1, 162, 101, 50, 5, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4, 255, 5, 128, 163, 116, 119, 111, 129, 100, 130, 6 });

    try testing.expectEqual(@as(c_int, 2), state.locals.*.count); // transient data survives
    try testing.expectEqual(@as(c_int, 2), state.units.*.count);
}

test "resync_plain_additive" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 162, 101, 49, 3, 255, 3, 128, 163, 111, 110, 101, 129, 100, 130, 4 });
    decode(decoder, &[_]u8{ 255, 1, 128, 1, 162, 101, 50, 5, 255, 5, 128, 163, 116, 119, 111, 129, 100, 130, 6 });
    // (a DELETE patch for e1 was dropped — never delivered)
    decode(decoder, &[_]u8{ 255, 5, 129, 42 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));
    try testing.expectEqual(@as(c_int, 2), state.units.*.count); // plain decode stays additive

    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 1, 162, 101, 50, 5, 255, 5, 128, 163, 116, 119, 111, 129, 42, 130, 6 });

    try testing.expectEqual(@as(c_int, 1), state.units.*.count); // resync reconciles
    try testing.expectEqual(@as(f64, 42), unitAt(state.units, "e2").?.hp);
}

test "resync_tail_trim" {
    const decoder = c.colyseus_decoder_create(&c.resync_state_vtable).?;
    defer c.colyseus_decoder_free(decoder);

    decode(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 164, 104, 101, 114, 111, 3, 255, 3, 128, 164, 104, 101, 114, 111, 129, 100, 130, 4, 255, 4, 128, 0, 5, 128, 1, 6, 128, 2, 7, 128, 3, 8, 255, 5, 128, 0, 255, 6, 128, 1, 255, 7, 128, 2, 255, 8, 128, 3 });

    const state: *c.resync_state_t = @ptrCast(@alignCast(c.colyseus_decoder_get_state(decoder)));

    // offline: hero lost the last two gems
    decodeResync(decoder, &[_]u8{ 128, 1, 129, 2, 255, 1, 128, 0, 164, 104, 101, 114, 111, 3, 255, 3, 128, 164, 104, 101, 114, 111, 129, 100, 130, 4, 255, 4, 128, 0, 5, 128, 1, 6, 255, 5, 128, 0, 255, 6, 128, 1 });

    const gems = unitAt(state.units, "hero").?.gems;
    try testing.expectEqual(@as(c_int, 2), gems.*.count);
    try testing.expectEqual(@as(f64, 0), gemPriceAt(gems, 0));
    try testing.expectEqual(@as(f64, 1), gemPriceAt(gems, 1));
    try testing.expectEqual(@as(usize, 7), refsCount(decoder));
}
