const std = @import("std");
const testing = std.testing;

// ============================================================================
// 0.18 wire-compat (Phase 0) — room-level protocol frames.
//
// Fixtures below generated by colyseus-0.18
// PORTING/generate-phase0-fixtures.cts (self-verified against the JS
// packages/sdk Room). See PORTING/sdk-coverage-plan-0.18.md.
//
// Frames are fed through colyseus_room_process_message() with a stub
// transport capturing outgoing bytes — no server needed.
// ============================================================================

const c = @cImport({
    @cInclude("colyseus/protocol.h");
    @cInclude("colyseus/transport.h");
    @cInclude("colyseus/room.h");
    @cInclude("colyseus/schema.h");
    @cInclude("schema/p0_state.h");
});

// ─── stub transport: captures outgoing frames ───────────────────────────────

var sent_frames: [8][64]u8 = undefined;
var sent_lens: [8]usize = undefined;
var sent_count: usize = 0;

fn stubSend(transport: [*c]c.colyseus_transport_t, data: [*c]const u8, length: usize) callconv(.c) void {
    _ = transport;
    if (sent_count < sent_frames.len and length <= 64) {
        @memcpy(sent_frames[sent_count][0..length], data[0..length]);
        sent_lens[sent_count] = length;
        sent_count += 1;
    }
}

fn stubIsOpen(transport: [*c]const c.colyseus_transport_t) callconv(.c) bool {
    _ = transport;
    return true;
}

var stub_transport = std.mem.zeroInit(c.colyseus_transport_t, .{});

fn makeRoom() *c.colyseus_room_t {
    sent_count = 0;
    stub_transport.send = stubSend;
    stub_transport.is_open = stubIsOpen;

    const room = c.colyseus_room_create("phase0", null).?;
    c.colyseus_room_set_state_type(room, &c.p0_state_vtable);
    room.*.transport = &stub_transport;
    return room;
}

fn destroyRoom(room: *c.colyseus_room_t) void {
    room.*.transport = null; // the stub is not heap-allocated
    c.colyseus_room_free(room);
}

fn feed(room: *c.colyseus_room_t, frame: []const u8) void {
    c.colyseus_room_process_message(room, frame.ptr, frame.len);
}

fn statePtr(room: *c.colyseus_room_t) *c.p0_state_t {
    const state = c.colyseus_room_get_state(room);
    return @ptrCast(@alignCast(state.?));
}

// ─── scenarios ──────────────────────────────────────────────────────────────

test "join_room_full_handshake" {
    const room = makeRoom();
    defer destroyRoom(room);

    // JOIN_ROOM with length-prefixed state reflection + INPUT_REFLECTION and
    // INPUT_OPTIONS tagged sections (room uses defineInput())
    feed(room, &[_]u8{ 10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2 });

    try testing.expect(room.*.has_joined);
    try testing.expectEqualStrings("tok123", std.mem.span(room.*.reconnection_token));

    // acknowledged with a single JOIN_ROOM byte
    try testing.expectEqual(@as(usize, 1), sent_count);
    try testing.expectEqual(@as(usize, 1), sent_lens[0]);
    try testing.expectEqual(@as(u8, 10), sent_frames[0][0]);

    // full state decodes through the real schema serializer
    feed(room, &[_]u8{ 14, 128, 165, 104, 101, 108, 108, 111, 129, 42 });
    try testing.expectEqualStrings("hello", std.mem.span(statePtr(room).msg));
    try testing.expectEqual(@as(f64, 42), statePtr(room).n);

    // TIMED-modified patch (143 = 15 | 0x80): the 8-byte
    // [uint32 sNow][uint32 inputSeq] prefix must be consumed
    feed(room, &[_]u8{ 143, 64, 226, 1, 0, 7, 0, 0, 0, 129, 43 });
    try testing.expectEqual(@as(f64, 43), statePtr(room).n);
}

test "join_room_reconnect" {
    const room = makeRoom();
    defer destroyRoom(room);

    // plain room: state reflection only, no trailing sections
    feed(room, &[_]u8{ 10, 4, 116, 111, 107, 65, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114 });
    try testing.expect(room.*.has_joined);
    const serializer_before = room.*.serializer;

    // reconnect JOIN: zero-length state reflection — the serializer (and its
    // state identity) must survive
    feed(room, &[_]u8{ 10, 4, 116, 111, 107, 66, 6, 115, 99, 104, 101, 109, 97, 0 });
    try testing.expect(room.*.has_joined);
    try testing.expectEqual(serializer_before, room.*.serializer);
    try testing.expectEqualStrings("tokB", std.mem.span(room.*.reconnection_token));
}

test "request_frame_encoding" {
    const room = makeRoom();
    defer destroyRoom(room);

    var replies: usize = 0;
    const on_response = struct {
        fn cb(ok: bool, reader: ?*c.colyseus_message_reader_t, err: [*c]const u8, userdata: ?*anyopaque) callconv(.c) void {
            _ = ok;
            _ = reader;
            _ = err;
            const count: *usize = @ptrCast(@alignCast(userdata.?));
            count.* += 1;
        }
    }.cb;

    const payload = [_]u8{7}; // msgpack 7
    _ = c.colyseus_room_request_encoded(room, "move", &payload, payload.len, on_response, &replies);

    // [21][requestId 0]['move' fixstr][msgpack 7]
    try testing.expectEqual(@as(usize, 1), sent_count);
    try testing.expectEqualSlices(u8, &[_]u8{ 21, 0, 164, 109, 111, 118, 101, 7 }, sent_frames[0][0..sent_lens[0]]);
    try testing.expectEqual(@as(usize, 0), replies);
}

const Outcome = struct {
    ok: bool = false,
    faulted: bool = false,
    has_reader: bool = false,
    replied: bool = false,
};

fn onOutcome(ok: bool, reader: ?*c.colyseus_message_reader_t, err: [*c]const u8, userdata: ?*anyopaque) callconv(.c) void {
    const outcome: *Outcome = @ptrCast(@alignCast(userdata.?));
    outcome.replied = true;
    outcome.ok = ok;
    outcome.faulted = (err != null);
    outcome.has_reader = (reader != null);
}

test "request_response_outcomes" {
    const room = makeRoom();
    defer destroyRoom(room);

    var outcomes = [_]Outcome{.{}} ** 4;

    // ids mint from 0 in order
    _ = c.colyseus_room_request_encoded(room, "a", null, 0, onOutcome, &outcomes[0]);
    _ = c.colyseus_room_request_encoded(room, "b", null, 0, onOutcome, &outcomes[1]);
    _ = c.colyseus_room_request_encoded(room, "c", null, 0, onOutcome, &outcomes[2]);
    _ = c.colyseus_room_request_encoded(room, "d", null, 0, onOutcome, &outcomes[3]);

    feed(room, &[_]u8{ 22, 0, 0, 42 });                      // OK, payload 42
    feed(room, &[_]u8{ 22, 1, 0 });                          // OK, no payload
    feed(room, &[_]u8{ 22, 2, 1, 164, 110, 111, 112, 101 }); // REJECTED, "nope"
    feed(room, &[_]u8{ 22, 3, 2, 222, 0, 2, 164, 110, 97, 109, 101, 165, 69, 114, 114, 111, 114, 167, 109, 101, 115, 115, 97, 103, 101, 164, 98, 111, 111, 109 }); // ERROR, {name,message}
    feed(room, &[_]u8{ 22, 205, 231, 3, 0, 1 });             // unknown id 999 — ignored

    try testing.expect(outcomes[0].replied and outcomes[0].ok and outcomes[0].has_reader and !outcomes[0].faulted);
    try testing.expect(outcomes[1].replied and outcomes[1].ok and !outcomes[1].has_reader);
    try testing.expect(outcomes[2].replied and !outcomes[2].ok and outcomes[2].has_reader and !outcomes[2].faulted);
    try testing.expect(outcomes[3].replied and !outcomes[3].ok and outcomes[3].has_reader and outcomes[3].faulted);
}

test "cancel_request_ignores_late_response" {
    const room = makeRoom();
    defer destroyRoom(room);

    var outcome = Outcome{};
    const request_id = c.colyseus_room_request_encoded(room, "a", null, 0, onOutcome, &outcome);

    c.colyseus_room_cancel_request(room, request_id);
    feed(room, &[_]u8{ 22, 0, 0, 42 });

    try testing.expect(!outcome.replied);
}
