#!/usr/bin/env bash
#
# Publish the Swift package to colyseus/colyseus-swift.
#
# SwiftPM resolves a package from a repository ROOT and only understands plain
# semver tags, so it cannot see a manifest under platforms/ or a tag named
# swift-v0.18.0. The mirror gives it both, and spares consumers a 300 MB clone
# of a repo whose submodules the Swift package never uses.
#
# Generated, never edited by hand: every release rewrites main.
#
#   ./mirror.sh 0.18.1 <sha256> [--dry-run]
#
# The checksum is the one build.sh writes next to the archive, which is what
# `swift package compute-checksum` produces.

set -euo pipefail

VERSION="${1:?usage: mirror.sh <version> <checksum> [--dry-run]}"
CHECKSUM="${2:?usage: mirror.sh <version> <checksum> [--dry-run]}"
DRY_RUN="${3:-}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
STAGE="$(mktemp -d)"
REMOTE="${MIRROR_REMOTE:-https://github.com/colyseus/colyseus-swift.git}"
ARCHIVE="https://github.com/colyseus/native-sdk/releases/download/v${VERSION}/Colyseus.xcframework.zip"

trap 'rm -rf "$STAGE"' EXIT

# What a consumer needs, and nothing else: no build.zig, no submodules, no
# xcframework sources. The binary arrives from the native-sdk release.
cp -R "$HERE/Sources" "$STAGE/Sources"
cp -R "$HERE/Tests" "$STAGE/Tests"
cp "$HERE/CHANGELOG.md" "$STAGE/CHANGELOG.md"
cp "$ROOT/LICENSE" "$STAGE/LICENSE"
printf '.build/\n' > "$STAGE/.gitignore"

cat > "$STAGE/Package.swift" <<EOF
// swift-tools-version: 6.0
import PackageDescription

// Generated by platforms/swift/mirror.sh in colyseus/native-sdk — edit it there.
//
// The core is Zig as much as it is C — msgpack, http and the certificate store
// are Zig modules — so SwiftPM cannot compile it from source. It arrives as a
// pre-built xcframework, pinned here to the release this tag was cut from.

let package = Package(
    name: "Colyseus",
    platforms: [
        .macOS(.v13),
        .iOS(.v15),
        .tvOS(.v15),
    ],
    products: [
        .library(name: "Colyseus", targets: ["Colyseus"]),
    ],
    targets: [
        .target(
            name: "Colyseus",
            dependencies: ["CColyseus"],
            path: "Sources/Colyseus",
            swiftSettings: [.swiftLanguageMode(.v6)],
            linkerSettings: [
                // A static library in an xcframework carries no dependency
                // information, so the frameworks the core reaches for — the
                // keychain, the system certificate store — are linked here.
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security"),
            ]
        ),
        .binaryTarget(
            name: "CColyseus",
            url: "${ARCHIVE}",
            checksum: "${CHECKSUM}"
        ),
        .testTarget(
            name: "ColyseusTests",
            dependencies: ["Colyseus", "CColyseus"],
            path: "Tests/ColyseusTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
EOF

cat > "$STAGE/README.md" <<EOF
# Colyseus SDK for Swift

Swift over the [Colyseus native SDK](https://github.com/colyseus/native-sdk),
for macOS, iOS and tvOS.

\`\`\`swift
.package(url: "https://github.com/colyseus/colyseus-swift", from: "${VERSION}")
\`\`\`

\`\`\`swift
let client = try Colyseus.Client(endpoint: "ws://localhost:2567")
let room = try await client.joinOrCreate("my_room", state: MyRoomState.self)

let callbacks = Colyseus.Callbacks.get(room)
callbacks.onAdd(room.state!.players) { sessionId, player in
    spawn(sessionId, at: player.x, player.y)
}
\`\`\`

The frame loop, the prediction layer and the rest of the API are documented in
[platforms/swift/README.md](https://github.com/colyseus/native-sdk/blob/main/platforms/swift/README.md).

---

> **This repository is generated.** It is published from
> [colyseus/native-sdk](https://github.com/colyseus/native-sdk)'s
> \`platforms/swift\` on every release, and \`main\` is rewritten each time — a
> commit made here would be overwritten.
>
> **Issues and pull requests belong in
> [colyseus/native-sdk](https://github.com/colyseus/native-sdk/issues).**
EOF

mkdir -p "$STAGE/.github"
cat > "$STAGE/.github/PULL_REQUEST_TEMPLATE.md" <<'EOF'
> This repository is a generated mirror — `main` is replaced on every release,
> so a change merged here would not survive the next one.
>
> Please open this against
> [colyseus/native-sdk](https://github.com/colyseus/native-sdk), under
> `platforms/swift`. Thank you!
EOF


echo "staged $(find "$STAGE" -type f | wc -l | tr -d ' ') files in $STAGE"
echo "  archive:  $ARCHIVE"
echo "  checksum: $CHECKSUM"

if [ "$DRY_RUN" = "--dry-run" ]; then
  KEEP="${STAGE}-kept"
  cp -R "$STAGE" "$KEEP"
  echo "dry run — kept at $KEEP"
  exit 0
fi

# Update the mirror in place rather than force-pushing a fresh history: it
# keeps a readable log across versions, and it leaves the repository's own
# furniture — .github/workflows above all — untouched. GitHub refuses a push
# that creates or updates a workflow unless the token carries `workflow`
# scope, which a release token has no other reason to hold.
WORK="$(mktemp -d)"
trap 'rm -rf "$STAGE" "$WORK"' EXIT
git clone -q --depth 1 "$REMOTE" "$WORK"

cd "$WORK"
rm -rf Sources Tests Package.swift README.md CHANGELOG.md LICENSE .gitignore \
       .github/PULL_REQUEST_TEMPLATE.md
cp -R "$STAGE/." .

git add -A
if git diff --cached --quiet; then
  echo "mirror already matches ${VERSION}"
else
  git -c user.name="colyseus-bot" -c user.email="bot@colyseus.io" \
    commit -q -m "Colyseus Swift SDK ${VERSION}

Generated from colyseus/native-sdk platforms/swift."
fi
git tag -f "v${VERSION}"
git push -q "$REMOTE" HEAD:main
git push -q --force "$REMOTE" "v${VERSION}"
echo "pushed main and v${VERSION} to $REMOTE"
